nome = str(input('Digite seu nome completo:')).strip()
nome = nome.capitalize()
dividido = nome.split()
print('Primeiro nome: {}'.format(dividido[0]))
print('Ultimo nome: {}'.format(dividido[len(dividido)-1]))